# Generated by Django 3.1.12 on 2025-07-09 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_auto_20250709_0848'),
    ]

    operations = [
        migrations.AddField(
            model_name='classrooms',
            name='edited_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
