# Generated by Django 3.1.12 on 2025-07-10 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_classrooms_edited_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='classrooms',
            name='school',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
