# Generated by Django 3.1.12 on 2025-07-10 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_classrooms_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='classrooms',
            name='slug_name',
            field=models.SlugField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='classrooms',
            name='slug_school',
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
    ]
