# Generated by Django 3.1.12 on 2025-07-10 11:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tracker', '0006_auto_20250710_1835'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreeViewSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_notes', models.BooleanField(default=False)),
                ('notes_count', models.IntegerField(default=1)),
                ('show_stars', models.BooleanField(default=False)),
                ('stars_count', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='treeview_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
