# Generated by Django 5.2.4 on 2025-07-10 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_treeviewsettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treeviewsettings',
            name='notes_count',
        ),
        migrations.RemoveField(
            model_name='treeviewsettings',
            name='stars_count',
        ),
        migrations.AddField(
            model_name='students',
            name='stars_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
