# Generated by Django 5.2.4 on 2025-07-12 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_remove_treeviewsettings_notes_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classrooms',
            name='notes_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
