# Generated by Django 5.2.4 on 2025-07-12 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_classrooms_notes_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='note_overall',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='notes',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
